# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_acsi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 596)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("upch_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graph_1 = QtWidgets.QLabel(self.centralwidget)
        self.graph_1.setGeometry(QtCore.QRect(10, 130, 331, 291))
        self.graph_1.setStyleSheet("QLabel{\n"
"border-color: rgb(27, 38, 30);\n"
"background-color: rgb(245, 245, 245);\n"
"border-style:outset;\n"
"border-radius: 2px;\n"
"border-width: 1px;\n"
"}")
        self.graph_1.setText("")
        self.graph_1.setScaledContents(True)
        self.graph_1.setObjectName("graph_1")
        self.l_frame = QtWidgets.QLabel(self.centralwidget)
        self.l_frame.setGeometry(QtCore.QRect(250, 79, 41, 31))
        self.l_frame.setStyleSheet("QLabel{\n"
"color: rgb(6, 5, 50);\n"
"font: 8pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(167, 190, 203);\n"
"border-style:outset;\n"
"border-radius: 4px;\n"
"border-width: 1px;\n"
"padding: 2px;\n"
"border-color: rgb(34, 48, 38);\n"
"}")
        self.l_frame.setObjectName("l_frame")
        self.choose = QtWidgets.QPushButton(self.centralwidget)
        self.choose.setGeometry(QtCore.QRect(350, 82, 91, 31))
        self.choose.setStyleSheet("QPushButton{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(221, 230, 237);\n"
"border-style:outset;\n"
"border-top-left-radius: 4px;\n"
"border-radius: 4px;\n"
"border-width: 1.5px;\n"
"padding: 2px;\n"
"border-color: rgb(27, 38, 30);\n"
"}")
        self.choose.setObjectName("choose")
        self.t_vol_h = QtWidgets.QTextEdit(self.centralwidget)
        self.t_vol_h.setGeometry(QtCore.QRect(550, 480, 71, 31))
        self.t_vol_h.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.t_vol_h.setStyleSheet("QTextEdit{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(167, 190, 203);\n"
"border-style:outset;\n"
"border-top-left-radius: 4px;\n"
"border-radius: 4px;\n"
"border-width: 1px;\n"
"padding: 2px;\n"
"border-color: rgb(34, 48, 38);\n"
"}")
        self.t_vol_h.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.t_vol_h.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.t_vol_h.setReadOnly(True)
        self.t_vol_h.setObjectName("t_vol_h")
        self.graph_2 = QtWidgets.QLabel(self.centralwidget)
        self.graph_2.setGeometry(QtCore.QRect(360, 130, 331, 291))
        self.graph_2.setStyleSheet("QLabel{\n"
"border-color: rgb(27, 38, 30);\n"
"background-color: rgb(245, 245, 245);\n"
"border-style:outset;\n"
"border-radius: 2px;\n"
"border-width: 1px;\n"
"}")
        self.graph_2.setText("")
        self.graph_2.setScaledContents(True)
        self.graph_2.setObjectName("graph_2")
        self.l_vol_h = QtWidgets.QLabel(self.centralwidget)
        self.l_vol_h.setGeometry(QtCore.QRect(430, 480, 111, 31))
        self.l_vol_h.setStyleSheet("QLabel{\n"
"color: rgb(6, 5, 50);\n"
"font: 8pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(167, 190, 203);\n"
"border-style:outset;\n"
"border-radius: 4px;\n"
"border-width: 1px;\n"
"padding: 2px;\n"
"border-color: rgb(34, 48, 38);\n"
"}")
        self.l_vol_h.setObjectName("l_vol_h")
        self.save_file = QtWidgets.QPushButton(self.centralwidget)
        self.save_file.setGeometry(QtCore.QRect(100, 480, 141, 41))
        self.save_file.setStyleSheet("QPushButton{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(221, 230, 237);\n"
"border-style:outset;\n"
"border-top-left-radius: 4px;\n"
"border-radius: 4px;\n"
"border-width: 1.5px;\n"
"padding: 2px;\n"
"border-color: rgb(27, 38, 30);\n"
"}")
        self.save_file.setObjectName("save_file")
        self.load_file = QtWidgets.QComboBox(self.centralwidget)
        self.load_file.setGeometry(QtCore.QRect(110, 30, 131, 41))
        self.load_file.setStyleSheet("QComboBox{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(221, 230, 237);\n"
"border-style:outset;\n"
"border-top-left-radius: 4px;\n"
"border-radius: 4px;\n"
"border-width: 1.5px;\n"
"padding: 2px;\n"
"border-color: rgb(27, 38, 30);\n"
"}")
        self.load_file.setEditable(False)
        self.load_file.setMinimumContentsLength(0)
        self.load_file.setObjectName("load_file")
        self.load_file.addItem("")
        self.load_file.addItem("")
        self.play_both = QtWidgets.QPushButton(self.centralwidget)
        self.play_both.setGeometry(QtCore.QRect(320, 440, 75, 23))
        self.play_both.setStyleSheet("QPushButton{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(221, 230, 237);\n"
"border-style:outset;\n"
"border-top-left-radius: 4px;\n"
"border-radius: 4px;\n"
"border-width: 1.5px;\n"
"padding: 2px;\n"
"border-color: rgb(27, 38, 30);\n"
"}")
        self.play_both.setObjectName("play_both")
        self.stop_both = QtWidgets.QPushButton(self.centralwidget)
        self.stop_both.setGeometry(QtCore.QRect(400, 440, 51, 23))
        self.stop_both.setStyleSheet("QPushButton{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(221, 230, 237);\n"
"border-style:outset;\n"
"border-top-left-radius: 4px;\n"
"border-radius: 4px;\n"
"border-width: 1.5px;\n"
"padding: 2px;\n"
"border-color: rgb(27, 38, 30);\n"
"}")
        self.stop_both.setObjectName("stop_both")
        self.next_both = QtWidgets.QPushButton(self.centralwidget)
        self.next_both.setGeometry(QtCore.QRect(270, 440, 41, 23))
        self.next_both.setStyleSheet("QPushButton{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(221, 230, 237);\n"
"border-style:outset;\n"
"border-top-left-radius: 4px;\n"
"border-radius: 4px;\n"
"border-width: 1.5px;\n"
"padding: 2px;\n"
"border-color: rgb(27, 38, 30);\n"
"}")
        self.next_both.setObjectName("next_both")
        self.start_op = QtWidgets.QPushButton(self.centralwidget)
        self.start_op.setGeometry(QtCore.QRect(450, 30, 161, 41))
        self.start_op.setStyleSheet("QPushButton{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(221, 230, 237);\n"
"border-style:outset;\n"
"border-radius: 4px;\n"
"border-width: 1.5px;\n"
"padding: 2px;\n"
"border-color: rgb(27, 38, 30);\n"
"}")
        self.start_op.setObjectName("start_op")
        self.back_both = QtWidgets.QPushButton(self.centralwidget)
        self.back_both.setGeometry(QtCore.QRect(220, 440, 41, 23))
        self.back_both.setStyleSheet("QPushButton{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(221, 230, 237);\n"
"border-style:outset;\n"
"border-top-left-radius: 4px;\n"
"border-radius: 4px;\n"
"border-width: 1.5px;\n"
"padding: 2px;\n"
"border-color: rgb(27, 38, 30);\n"
"}")
        self.back_both.setObjectName("back_both")
        self.t_frame = QtWidgets.QTextEdit(self.centralwidget)
        self.t_frame.setGeometry(QtCore.QRect(300, 80, 41, 31))
        self.t_frame.setStyleSheet("QTextEdit{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(167, 190, 203);\n"
"border-style:outset;\n"
"border-radius: 4px;\n"
"border-width: 1px;\n"
"padding: 2px;\n"
"border-color: rgb(34, 48, 38);\n"
"}")
        self.t_frame.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.t_frame.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.t_frame.setReadOnly(True)
        self.t_frame.setObjectName("t_frame")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(250, 10, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(23)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_titulo.setFont(font)
        self.label_titulo.setAutoFillBackground(False)
        self.label_titulo.setStyleSheet("QLabel{\n"
"    font: 22.5pt \"MS Reference Sans Serif\";\n"
"color: rgb(221, 230, 237);\n"
"background-color:rgb(82, 109, 130);\n"
"border-style:outset;\n"
"border-top-left-radius: 4px;\n"
"border-radius: 15px;\n"
"border-width: 1.5px;\n"
"padding: 2px;\n"
"border-color: rgb(27, 38, 30);\n"
"}\n"
"")
        self.label_titulo.setWordWrap(False)
        self.label_titulo.setIndent(-2)
        self.label_titulo.setObjectName("label_titulo")
        self.button_info = QtWidgets.QPushButton(self.centralwidget)
        self.button_info.setGeometry(QtCore.QRect(590, 540, 101, 31))
        self.button_info.setStyleSheet("QPushButton{\n"
"color: rgb(6, 5, 50);\n"
"font: 9pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(221, 230, 237);\n"
"border-style:outset;\n"
"border-top-left-radius: 4px;\n"
"border-radius: 4px;\n"
"border-width: 1.5px;\n"
"padding: 2px;\n"
"border-color: rgb(27, 38, 30);\n"
"}")
        self.button_info.setObjectName("button_info")
        self.label_carrera = QtWidgets.QLabel(self.centralwidget)
        self.label_carrera.setGeometry(QtCore.QRect(20, 540, 141, 31))
        self.label_carrera.setObjectName("label_carrera")
        self.logo_upch = QtWidgets.QLabel(self.centralwidget)
        self.logo_upch.setGeometry(QtCore.QRect(160, 530, 111, 51))
        self.logo_upch.setAutoFillBackground(False)
        self.logo_upch.setText("")
        self.logo_upch.setPixmap(QtGui.QPixmap("upch_logo.png"))
        self.logo_upch.setScaledContents(True)
        self.logo_upch.setObjectName("logo_upch")
        self.logo_pucp = QtWidgets.QLabel(self.centralwidget)
        self.logo_pucp.setGeometry(QtCore.QRect(270, 530, 101, 51))
        self.logo_pucp.setText("")
        self.logo_pucp.setPixmap(QtGui.QPixmap("pucp_logo.png"))
        self.logo_pucp.setScaledContents(True)
        self.logo_pucp.setObjectName("logo_pucp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.l_frame.setText(_translate("MainWindow", " Slice:"))
        self.choose.setText(_translate("MainWindow", "Escoger slice"))
        self.t_vol_h.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe MDL2 Assets\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.l_vol_h.setText(_translate("MainWindow", "Volumen Hipocampo:"))
        self.save_file.setText(_translate("MainWindow", "Guardar archivos"))
        self.load_file.setItemText(0, _translate("MainWindow", "Cargar NIfTI"))
        self.load_file.setItemText(1, _translate("MainWindow", "Cargar DICOM"))
        self.play_both.setText(_translate("MainWindow", "Reproducir"))
        self.stop_both.setText(_translate("MainWindow", "Stop"))
        self.next_both.setText(_translate("MainWindow", "->"))
        self.start_op.setText(_translate("MainWindow", "Iniciar Cálculo Volumétrico"))
        self.back_both.setText(_translate("MainWindow", "<-"))
        self.label_titulo.setText(_translate("MainWindow", " HippoSeg"))
        self.button_info.setText(_translate("MainWindow", "Información (?)"))
        self.label_carrera.setText(_translate("MainWindow", "Ingeniería Biomédica - 2023"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
