# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_acsi_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tercera_ventana(object):
    def setupUi(self, tercera_ventana):
        tercera_ventana.setObjectName("tercera_ventana")
        tercera_ventana.resize(527, 306)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("upch_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tercera_ventana.setWindowIcon(icon)
        tercera_ventana.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.centralwidget = QtWidgets.QWidget(tercera_ventana)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.label.setStyleSheet("QLabel{\n"
"color: rgb(6, 5, 50);\n"
"font: 8pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(167, 190, 203);\n"
"border-style:outset;\n"
"border-radius: 4px;\n"
"border-width: 1px;\n"
"padding: 2px;\n"
"border-color: rgb(34, 48, 38);\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 61, 221, 20))
        self.label_2.setStyleSheet("background-color:rgb(235, 230, 234);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 461, 21))
        self.label_3.setStyleSheet("background-color:rgb(235, 230, 234);\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 421, 16))
        self.label_4.setStyleSheet("background-color:rgb(235, 230, 234);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 481, 21))
        self.label_5.setStyleSheet("background-color:rgb(235, 230, 234);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 210, 451, 21))
        self.label_6.setStyleSheet("background-color:rgb(235, 230, 234);\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 120, 451, 21))
        self.label_7.setStyleSheet("background-color:rgb(235, 230, 234);\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 150, 451, 21))
        self.label_8.setStyleSheet("background-color:rgb(235, 230, 234);\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 51, 501, 221))
        self.label_9.setStyleSheet("QLabel{\n"
"color: rgb(6, 5, 50);\n"
"font: 8pt \"Segoe MDL2 Assets\";\n"
"background-color:rgb(235, 230, 234);\n"
"border-style:outset;\n"
"border-radius: 4px;\n"
"border-width: 1px;\n"
"padding: 2px;\n"
"border-color: rgb(34, 48, 38);\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_9.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        tercera_ventana.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(tercera_ventana)
        self.statusbar.setObjectName("statusbar")
        tercera_ventana.setStatusBar(self.statusbar)

        self.retranslateUi(tercera_ventana)
        QtCore.QMetaObject.connectSlotsByName(tercera_ventana)

    def retranslateUi(self, tercera_ventana):
        _translate = QtCore.QCoreApplication.translate
        tercera_ventana.setWindowTitle(_translate("tercera_ventana", "MainWindow"))
        self.label.setText(_translate("tercera_ventana", "INFORMACIÓN:"))
        self.label_2.setText(_translate("tercera_ventana", "1) Cargar la carpeta con los archivos DICOM"))
        self.label_3.setText(_translate("tercera_ventana", "2) Para la obtención del Volumen del Hipocampo, darle click al botón \"Iniciar Cálculo Volumétrico\""))
        self.label_4.setText(_translate("tercera_ventana", "7) Guardar los archivos correspondientes a la data segmentada y el volumen calculado  "))
        self.label_5.setText(_translate("tercera_ventana", "5) Para observar cada slice de la data, usar las flechas \"<-\" y \"->\", así como el botón \"Escoger Slice\""))
        self.label_6.setText(_translate("tercera_ventana", "6) Se cuenta con el botón de \"Reproducir\" y \"Stop\" para observar toda la secuencia de slices "))
        self.label_7.setText(_translate("tercera_ventana", "3) En el marco de la izquierda, se observarán slices del MRI de la data original"))
        self.label_8.setText(_translate("tercera_ventana", "4) En el marco de la derecha, se observarán slices del MRI de la data segmentada"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tercera_ventana = QtWidgets.QMainWindow()
    ui = Ui_tercera_ventana()
    ui.setupUi(tercera_ventana)
    tercera_ventana.show()
    sys.exit(app.exec_())
